## indicators that the featurize function watches for in a given string
indicators = [
    'CriOS',
    'FxiOS',
    'MSIE',
    'IEMobile',
    'Edge',
    'Firefox',
    'OPR',
    'UCBrowser',
    'QQBrowser',
    'MQQBrowser',
    'Maxthon',
    'AOL',
    'FBAV',
    'Puffin',
    'YandexSearch',
    'RIM Tablet OS',
    'BB',
    'Silk',
    'CrMo',
    'Chrome',
    'Safari',
    'rv',
    'Android',
]

info_sources = {
    'Chrome':               ['Chrome', 'other_info'],
    'Chrome Mobile':        ['Chrome', 'other_info'],
    'Chrome Mobile iOS':    ['CriOS', 'other_info'],
    'Safari':               ['Version', 'other_info'],
    'Mobile Safari':        ['Version', 'other_info'],
    'IE':                   ['MSIE', 'dev_info'],
    'IE Mobile':            ['IEMobile', 'dev_info'],
    'Edge':                 ['Edge', 'other_info'],
    'Edge Mobile':          ['Edge', 'other_info'],
    'Firefox':              ['Firefox', 'other_info'],
    'Firefox Mobile':       ['Firefox', 'other_info'],
    'Firefox iOS':          ['FxiOS', 'other_info'],
    'Opera':                ['OPR', 'other_info'],
    'Opera Mobile':         ['OPR', 'other_info'],
    'Opera Mini':           ['OPR', 'other_info'],
    'UC Browser':           ['UCBrowser', 'other_info'],
    'QQ Browser':           ['QQBrowser', 'other_info'],
    'QQ Browser Mobile':    ['MQQBrowser', 'other_info'],
    'Maxthon':              ['Maxthon', 'other_info'],
    'AOL':                  ['AOL', 'dev_info'],
    'Facebook':             ['FBAV', 'other_info'],
    'Puffin':               ['Puffin', 'other_info'],
    'YandexSearch':         ['YandexSearch', 'other_info'],
    'BlackBerry WebKit':    ['RIM Tablet OS', 'dev_info'],
    'Amazon Silk':          ['Silk', 'other_info'],
    'AppleMail':            ['AppleWebKit', 'other_info'],
    'Android':              ['Android', 'dev_info'],
}